### ISSUE TITLE
FYI - proposed changes at GH repo

### ISSUE THREAD

**Issue by jvonau** [arky/iiab-smoketest#6]
https://github.com/georgejhunt/iiab-smoketest/pull/1

Any reason the 2 repos are not linked as forks?

**Comment by arky** [comment]
My best guess is that George didn't use Github 'Fork' button to create that repo. 

Marking this bug as invalid.

**Comment by jvonau** [comment]
2 questions being a novice with Jenkin, but completely familiar with producing liveisos and images, adding a dependency for the build script just doesn't feel right. First does the change in the web-link look sane? Second, what needs to be done to have that change actually used by jenkin?

**Comment by arky** [comment]
@jvonau Am trying to refactor the 'curl-me' script into more sensible deployment script. Am bit distracted by getting ARM Raspbian build system ready at the moment. 

Just change the Jenkins build job to use 'https://github.com/georgejhunt/iiab-smoketest'  instead of this repo.

**Comment by jvonau** [comment]
I'd send a PR but I cloned from GH. I re-factored the curl me by distros, hope this helps the cause https://patch-diff.githubusercontent.com/raw/georgejhunt/iiab-smoketest/pull/1.patch

**Comment by arky** [comment]
Thanks @jvonau Added it to my todo list in #9
